kind = "web"
previewPath = "/"
title = "Directory Master"
version = "1.0.0"
id = "artifacts/directory-master"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19179

[services.development]
run = "pnpm --filter @workspace/directory-master run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/directory-master", "run", "build" ]
publicDir = "artifacts/directory-master/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19179"
BASE_PATH = "/"
